### PR TITLE
fix(icon): respond to changes of document dir

### LINKED ISSUE #1196: bug: flip-rtl behavior isn't reactive when document dir changes
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When I change the app to RTL, the ion-back-button arrow doesn't instantly changes to RTL, I need to change to another page to see the change.

### Expected Behavior

Right after change to RTL, the ion-back-button arrow turns 180 degrees.

### Steps to Reproduce

Navigate to a page with an ion-back-button, change document.documentElement.dir to 'rtl' and you will see that the arrow doesn't change

### Code Reproduction URL

https://github.com/FranciskoNeves/IonBackButtonRTL

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (C:\Users\Francisco.neves\AppData\Roaming\nvm\v16.13.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.6.0
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mapsandapps**
Resolves #1196

Use CSS to ensure that the icon's direction can change when needed*, if state changes after initial page load

`*` if the icon has the `flip-rtl` prop set or if it's an arrow or chevron or if the element has a `dir` attribute

### CODE REVIEW

File: src/components/icon/utils.ts [hunk 1]
```diff
@@ -140,17 +140,3 @@ export const inheritAttributes = (el: HTMLElement, attributes: string[] = []) =>
 
   return attributeObject;
 }
-
-/**
- * Returns `true` if the document or host element
- * has a `dir` set to `rtl`. The host value will always
- * take priority over the root document value.
- */
-export const isRTL = (hostEl?: Pick<HTMLElement, 'dir'>) => {
```
Comment (mapsandapps) [inline src/components/icon/utils.ts:149]: is this okay to remove? it's not used anywhere else

**Review by liamdebeasi — COMMENTED** [review]
Ionic Framework has some mixins that let us accomplish RTL styles without JavaScript: https://github.com/ionic-team/ionic-framework/blob/main/core/src/themes/ionic.mixins.scss

I know Maria had done some work to improve these mixins for broader browser compatibility, so I wonder if we could use that here. Her PR in https://github.com/ionic-team/ionic-framework/pull/27203, uses `:host-context` for Chrome support and `:dir` for Firefox/Safari support.

This would enable us to remove the MutationObserver and do something like this:

```css
:host(.flip-rtl) .icon-inner {
  @include rtl() {
    transform: scaleX(-1);
  }
}
```

`:host-context` is supported by all versions of Chrome/Edge that Ionic 7 supports: https://caniuse.com/?search=host-context
`:dir` is supported by all versions of Firefox that we support: https://caniuse.com/?search=%3Adir

Support for `:dir` in Safari is new, but this was determined to be an acceptable tradeoff in the Framework PR I mentioned above since iOS has a pretty solid upgrade rate.

File: src/components/icon/utils.ts (hunk 1 above)
Comment (liamdebeasi) [reply src/components/icon/utils.ts:149]: Yeah we can remove this if we aren't using it anymore.

File: src/components/icon/icon.tsx [hunk 2]
```diff
@@ -82,6 +88,9 @@ export class Icon {
 
   componentWillLoad() {
     this.inheritedAttributes = inheritAttributes(this.el, ['aria-label']);
+    this.shouldAutoFlip =
+      (this.iconName?.includes('arrow') || this.iconName?.includes('chevron')) && this.flipRtl !== false;
+    this.shouldBeFlippable = this.flipRtl || this.shouldAutoFlip || this.el.hasAttribute('dir');
```
Comment (liamdebeasi) [inline src/components/icon/icon.tsx:93]: This should probably stay in the `render` function in the event that the type of icon changes after page load. (Silly example: icon changes from `alarm` to `arrow-down`)

File: src/components/icon/icon.css [hunk 3]
```diff
@@ -33,15 +33,17 @@ svg {
...
  */
 
-:host(.flip-rtl) .icon-inner {
+:host(.flip-rtl):host-context([dir='rtl']) .icon-inner {
   transform: scaleX(-1);
 }
 
+:host(.flip-rtl:dir(rtl)) .icon-inner {
+  transform: scaleX(-1);
+}
```
Comment (liamdebeasi) [inline src/components/icon/icon.css:46]:
```suggestion
@supports selector(:dir(rtl)) {
  :host(.flip-rtl:dir(rtl)) .icon-inner {
    transform: scaleX(-1);
  }
}
```
Just to be safe, can we wrap this in an `@supports` check which is what the Framework mixin does?

**Review by liamdebeasi — COMMENTED** [review]
Did we create a dev build to verify that the original Ionic Framework issue is fixed?

File: src/components/icon/icon.tsx [hunk 4]
```diff
@@ -146,11 +151,11 @@ export class Icon {
   }
 
   render() {
-    const { iconName, el, inheritedAttributes } = this;
+    const { inheritedAttributes } = this;
```
Comment (liamdebeasi) [inline src/components/icon/icon.tsx:154]:
```suggestion
    const { iconName, inheritedAttributes, flipRtl } = this;
```

If we are accessing a class var multiple times we typically destructure. This will let you access just `flipRtl` instead of `this.flipRtl`

File: src/components/icon/icon.tsx [hunk 5]
```diff
@@ -159,7 +164,7 @@ export class Icon {
           [mode]: true,
           ...createColorClasses(this.color),
           [`icon-${this.size}`]: !!this.size,
-          'flip-rtl': !!flipRtl && isRTL(el),
+          'flip-rtl': Boolean(this.shouldBeFlippable),
```
Comment (liamdebeasi) [inline src/components/icon/icon.tsx:167]:
```suggestion
          'flip-rtl': shouldBeFlippable,
```

If we avoid the optional chaining then we likely don't need to coerce this to a boolean.

File: src/components/icon/test/icon.e2e.ts [hunk 6]
```diff
@@ -4,10 +4,49 @@ import { test } from '@utils/test/playwright';
...
+      document.dir = 'rtl';
+    });
+
+    await expect(autoflip).toHaveCSS('transform', /matrix\(-1/);
+    await expect(unflip).not.toHaveCSS('transform', /matrix\(-1/);
+
+    // Wait for all SVGs to be lazily loaded before taking screenshots
+    await page.waitForLoadState('networkidle');
+
+    expect(await page.screenshot({ fullPage: true })).toMatchSnapshot(`icon-rtl-diff.png`);
```
Comment (liamdebeasi) [inline src/components/icon/test/icon.e2e.ts:32]: Can we take screenshots of the specific icons we want to test rather than the entire page? In this case we can probably screenshot just the `.auto-flip-chevrons` and `.un-flip-chevrons` containers.

File: src/components/icon/test/icon.e2e.ts [hunk 7]
```diff
@@ -4,10 +4,49 @@ import { test } from '@utils/test/playwright';
...
+    await page.goto(`/`);
+
+    const autoflip = page.locator('.auto-flip-chevrons [name=chevron-forward] .icon-inner');
+    const unflip = page.locator('.un-flip-chevrons [name=chevron-forward] .icon-inner');
+    await expect(autoflip).not.toHaveCSS('transform', /matrix\(-1/);
+    await expect(unflip).not.toHaveCSS('transform', /matrix\(-1/);
+
+    await page.evaluate(() => {
+      document.dir = 'rtl';
+    });
```
Comment (liamdebeasi) [inline src/components/icon/test/icon.e2e.ts:24]: Is it possible to start the test with this pre-configured, or is that not what we are trying to test?

File: src/components/icon/icon.tsx [hunk 8]
```diff
@@ -146,11 +151,11 @@ export class Icon {
...
   render() {
-    const { iconName, el, inheritedAttributes } = this;
+    const { inheritedAttributes } = this;
     const mode = this.mode || 'md';
-    const flipRtl =
-      this.flipRtl ||
-      (iconName && (iconName.indexOf('arrow') > -1 || iconName.indexOf('chevron') > -1) && this.flipRtl !== false);
+    this.shouldAutoFlip =
+      (this.iconName?.includes('arrow') || this.iconName?.includes('chevron')) && this.flipRtl !== false;
+    this.shouldBeFlippable = this.flipRtl || this.shouldAutoFlip || this.el.hasAttribute('dir');
```
Comment (liamdebeasi) [inline src/components/icon/icon.tsx:158]:
```suggestion
    const shouldAutoFlip = (iconName && (iconName.indexOf('arrow') > -1 || iconName.indexOf('chevron') > -1) && flipRtl !== false);
    const shouldBeFlippable = flipRtl || shouldAutoFlip || this.el.hasAttribute('dir');
```

A few things:

1. IMO if we are always computing these values on `render` then there does not seem to be much value in caching them as global variables within the class. A local `const` should be fine here.
2. Using optional chaining has caused issues in the past with boolean/numeric values, so let's keep the old syntax just to be safe. (See https://github.com/ionic-team/ionic-framework/pull/25102 for an example)
3. Do we need `this.el.hasAttribute('dir')`? I believe `:dir()` should account for this. Or is this for browsers that support neither :host-context or :dir?

File: src/components/icon/test/icon.e2e.ts (hunk 6 above)
Comment (mapsandapps) [reply src/components/icon/test/icon.e2e.ts:32]: I think we should snapshot them all. Some should flip and some should not flip, and we should validate that nothing changes that would cause e.g. all of them to flip. I suppose I could change it to only capture the "RTL" section of the page, but I do think we should capture all of those.

File: src/components/icon/test/icon.e2e.ts (hunk 7 above)
Comment (mapsandapps) [reply src/components/icon/test/icon.e2e.ts:24]: No, both the assertions before and after this are important. This tests the original bug, which is that things were working fine in either `ltr` or `rtl`, but the icons weren't changing if the `dir` changed.

File: src/components/icon/icon.tsx (hunk 8 above)
Comment (mapsandapps) [reply src/components/icon/icon.tsx:158]: Oh yeah, good call on `this.el.hasAttribute('dir')`. I think that was left over from when there were observers.

**Comment by mapsandapps** [comment]
> Did we create a dev build to verify that the original Ionic Framework issue is fixed?

Took me a while to figure out how to do this 😅 I guess you have to create an Ionicons dev build and then make a branch of framework that uses that Ionicons build and then make a dev build of framework?

Anyway, it does indeed work with the reproduction from the original ticket!

```
    "@ionic/angular": "7.0.8-dev.11684448544.19bd9148",
    "ionicons": "7.1.1-dev.11684440744.15dddc23",
```

File: src/components/icon/test/icon.e2e.ts (hunk 6 above)
Comment (liamdebeasi) [reply src/components/icon/test/icon.e2e.ts]: Sure that works 👍

File: src/components/icon/test/icon.e2e.ts (hunk 7 above)
Comment (liamdebeasi) [reply src/components/icon/test/icon.e2e.ts:24]: Ahhh ok makes sense. Thanks!

**Review by liamdebeasi — APPROVED** [review]
Great job!
